[[constraint]]
  branch = "master"
  name = "github.com/ajstarks/svgo"

[[constraint]]
  name = "github.com/fredericlemoine/bitset"
  version = "1.2.0"

[[constraint]]
  name = "github.com/fredericlemoine/goalign"
  version = "0.2.5"

[[constraint]]
  name = "github.com/fredericlemoine/gostats"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/freetype"

[[constraint]]
  branch = "master"
  name = "github.com/jlaffaye/ftp"

[[constraint]]
  branch = "master"
  name = "github.com/llgcode/draw2d"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/image"
